# Generated by Django 5.2.13 on 2026-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
